version: "3.9"
services:
  proxy:
    image: appritstore-front
    container_name: appritstore-front
    build:
      dockerfile: proxy-dev.Dockerfile
    ports:
      - "80:80"
  api:
    image: appritstore-back
    container_name: appritstore-api
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FRONT_HOST=http://localhost
      - API_HOST_CALLBACK=localhost
      - PROFILE=DEV
      - API_PORT=9000
      - DATABASE_ADDRESS=db
    env_file:
      - ./docker-compose-api.env
  db:
    container_name: appritstore-db
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - ./docker-compose-mysql.env
    volumes:
      - my-datavolume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
volumes:
  my-datavolume: