version: '3.9'

services:
  front:
    image: apprit.azurecr.io/apprit/appritstore:81e41985e45f2c802a60f7c8dd2f852792e9afeb
    ports:
      - "8080:80"
    restart: always
    environment:
      - PORT=8080
      - REACT_APP_API_BASE_URL=https://api:9000/api/v1
  api:
    image: apprit.azurecr.io/apprit/appritback:81e41985e45f2c802a60f7c8dd2f852792e9afeb
    restart: always
    environment:
      - API_PORT=9000
      - FRONT_HOST=https://apprit.azurewebsites.net