CREATE DATABASE IF NOT EXISTS '${MYSQL_DATABASE_DATABASE}';
CREATE USER '${MYSQL_DATABASE_USER}' IDENTIFIED BY '${MYSQL_DATABASE_PASSWORD}';
GRANT PRIVILEGE ON DATABASE '${MYSQL_DATABASE_DATABASE}' TO '${MYSQL_DATABASE_USER}';